import '../globals.css'

export const metadata = {
  title: 'Programa Contábil',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <>
     <main>{children}</main>
    </>
  )
}
